p8105_hw2_sl5685
================
Shumei Liu
2024-10-02

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.1     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.3     ✔ tidyr     1.3.1
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
```

### Problem 1

``` r
trans_ent = 
  read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
    col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) |> 
  janitor::clean_names() |> 
  select(
    line, station_name, station_latitude, station_longitude, 
    starts_with("route"), entry, vending, entrance_type, ada) |> 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))

trans_ent
```

    ## # A tibble: 1,868 × 19
    ##    line     station_name station_latitude station_longitude route1 route2 route3
    ##    <chr>    <chr>                   <dbl>             <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  2 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  3 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  4 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  5 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  6 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  7 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  8 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  9 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ## 10 4 Avenue 53rd St                  40.6             -74.0 R      <NA>   <NA>  
    ## # ℹ 1,858 more rows
    ## # ℹ 12 more variables: route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <chr>, route9 <chr>, route10 <chr>, route11 <chr>, entry <lgl>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>

This dataset contains 19 variables and 1,868 rows. The variables are
line, station_name, station_latitude, station_longitude, route1, route2,
route3, route4, route5, route6, route 7, route8, route9, route10,
route11, entry, vending, entrance_type and ada.

For the data cleaning, first read csv file and clean the names of each
columns. Then, select all the variables that we need and use `mutate`
convert data from character to a logical variable. The resulting dataset
is 1,868 x 19. These data are not tidy.

###### Distinct station

``` r
trans_ent |> 
  select(station_name, line) |> 
  distinct()
```

    ## # A tibble: 465 × 2
    ##    station_name             line    
    ##    <chr>                    <chr>   
    ##  1 25th St                  4 Avenue
    ##  2 36th St                  4 Avenue
    ##  3 45th St                  4 Avenue
    ##  4 53rd St                  4 Avenue
    ##  5 59th St                  4 Avenue
    ##  6 77th St                  4 Avenue
    ##  7 86th St                  4 Avenue
    ##  8 95th St                  4 Avenue
    ##  9 9th St                   4 Avenue
    ## 10 Atlantic Av-Barclays Ctr 4 Avenue
    ## # ℹ 455 more rows

There are 465 distinct stations.

###### ADA compliant

``` r
trans_ent |> 
  filter(ada == TRUE) |> 
  select(station_name, line) |> 
  distinct()
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # ℹ 74 more rows

84 stations are ADA compliant.

###### Proportion without vending

``` r
trans_ent |> 
  filter(vending == "NO") |> 
  pull(entry) |> 
  mean()
```

    ## [1] 0.3770492

###### Serve the A train

``` r
trans_ent |> 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") |> 
  filter(route == "A") |> 
  select(station_name, line) |> 
  distinct()
```

    ## # A tibble: 60 × 2
    ##    station_name                  line           
    ##    <chr>                         <chr>          
    ##  1 Times Square                  42nd St Shuttle
    ##  2 125th St                      8 Avenue       
    ##  3 145th St                      8 Avenue       
    ##  4 14th St                       8 Avenue       
    ##  5 168th St - Washington Heights 8 Avenue       
    ##  6 175th St                      8 Avenue       
    ##  7 181st St                      8 Avenue       
    ##  8 190th St                      8 Avenue       
    ##  9 34th St                       8 Avenue       
    ## 10 42nd St                       8 Avenue       
    ## # ℹ 50 more rows

###### Serve the A train and ADA compliant

``` r
trans_ent |> 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") |> 
  filter(route == "A", ada == TRUE) |> 
  select(station_name, line) |> 
  distinct()
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

### Problem 2

Mr. Trash Wheel

``` r
mr_df = 
  read_excel("data/202409 Trash Wheel Collection Data.xlsx", 
                      sheet = "Mr. Trash Wheel") %>%
  janitor::clean_names() |>
  select(-c(x15, x16)) |>
  drop_na() |>
  mutate(sports_balls = as.integer(round(sports_balls))) |>
  mutate(name = "Mr. Trash Wheel") |>
  relocate(name)
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
mr_df
```

    ## # A tibble: 629 × 15
    ##    name  dumpster month year  date                weight_tons volume_cubic_yards
    ##    <chr>    <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ##  1 Mr. …        1 May   2014  2014-05-16 00:00:00        4.31                 18
    ##  2 Mr. …        2 May   2014  2014-05-16 00:00:00        2.74                 13
    ##  3 Mr. …        3 May   2014  2014-05-16 00:00:00        3.45                 15
    ##  4 Mr. …        4 May   2014  2014-05-17 00:00:00        3.1                  15
    ##  5 Mr. …        5 May   2014  2014-05-17 00:00:00        4.06                 18
    ##  6 Mr. …        6 May   2014  2014-05-20 00:00:00        2.71                 13
    ##  7 Mr. …        7 May   2014  2014-05-21 00:00:00        1.91                  8
    ##  8 Mr. …        8 May   2014  2014-05-28 00:00:00        3.7                  16
    ##  9 Mr. …        9 June  2014  2014-06-05 00:00:00        2.52                 14
    ## 10 Mr. …       10 June  2014  2014-06-11 00:00:00        3.76                 18
    ## # ℹ 619 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>

Professor Trash Wheel

``` r
prof_df = 
  read_excel("data/202409 Trash Wheel Collection Data.xlsx", 
                      sheet = "Professor Trash Wheel") %>%
  janitor::clean_names() |>
  drop_na() |>
  mutate(year = as.character(year)) |>
  mutate(name = "Professor Trash Wheel") |>
  relocate(name)

prof_df
```

    ## # A tibble: 113 × 14
    ##    name  dumpster month year  date                weight_tons volume_cubic_yards
    ##    <chr>    <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ##  1 Prof…        1 Janu… 2017  2017-01-02 00:00:00        1.79                 15
    ##  2 Prof…        2 Janu… 2017  2017-01-30 00:00:00        1.58                 15
    ##  3 Prof…        3 Febr… 2017  2017-02-26 00:00:00        2.32                 18
    ##  4 Prof…        4 Febr… 2017  2017-02-26 00:00:00        3.72                 15
    ##  5 Prof…        5 Febr… 2017  2017-02-28 00:00:00        1.45                 15
    ##  6 Prof…        6 March 2017  2017-03-30 00:00:00        1.71                 15
    ##  7 Prof…        7 April 2017  2017-04-01 00:00:00        1.82                 15
    ##  8 Prof…        8 April 2017  2017-04-20 00:00:00        2.37                 15
    ##  9 Prof…        9 May   2017  2017-05-10 00:00:00        2.64                 15
    ## 10 Prof…       10 May   2017  2017-05-26 00:00:00        2.78                 15
    ## # ℹ 103 more rows
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>

Gwynnda Trash Wheel

``` r
ga_df = 
  read_excel("data/202409 Trash Wheel Collection Data.xlsx", 
                      sheet = "Gwynnda Trash Wheel") %>%
  janitor::clean_names() |>
  mutate(year = as.character(year)) |>
  mutate(name = "Gwynnda Trash Wheel") |>
  relocate(name)

ga_df
```

    ## # A tibble: 264 × 13
    ##    name  dumpster month year  date                weight_tons volume_cubic_yards
    ##    <chr>    <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ##  1 Gwyn…        1 July  2021  2021-07-03 00:00:00        0.93                 15
    ##  2 Gwyn…        2 July  2021  2021-07-07 00:00:00        2.26                 15
    ##  3 Gwyn…        3 July  2021  2021-07-07 00:00:00        1.62                 15
    ##  4 Gwyn…        4 July  2021  2021-07-16 00:00:00        1.76                 15
    ##  5 Gwyn…        5 July  2021  2021-07-30 00:00:00        1.53                 15
    ##  6 Gwyn…        6 Augu… 2021  2021-08-11 00:00:00        2.06                 15
    ##  7 Gwyn…        7 Augu… 2021  2021-08-14 00:00:00        1.9                  15
    ##  8 Gwyn…        8 Augu… 2021  2021-08-16 00:00:00        2.16                 15
    ##  9 Gwyn…        9 Augu… 2021  2021-08-16 00:00:00        2.6                  15
    ## 10 Gwyn…       10 Augu… 2021  2021-08-17 00:00:00        3.21                 15
    ## # ℹ 254 more rows
    ## # ℹ 6 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>

Binding rows

``` r
wheel_tidy = bind_rows(mr_df, prof_df, ga_df)
  
wheel_tidy
```

    ## # A tibble: 1,006 × 15
    ##    name  dumpster month year  date                weight_tons volume_cubic_yards
    ##    <chr>    <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ##  1 Mr. …        1 May   2014  2014-05-16 00:00:00        4.31                 18
    ##  2 Mr. …        2 May   2014  2014-05-16 00:00:00        2.74                 13
    ##  3 Mr. …        3 May   2014  2014-05-16 00:00:00        3.45                 15
    ##  4 Mr. …        4 May   2014  2014-05-17 00:00:00        3.1                  15
    ##  5 Mr. …        5 May   2014  2014-05-17 00:00:00        4.06                 18
    ##  6 Mr. …        6 May   2014  2014-05-20 00:00:00        2.71                 13
    ##  7 Mr. …        7 May   2014  2014-05-21 00:00:00        1.91                  8
    ##  8 Mr. …        8 May   2014  2014-05-28 00:00:00        3.7                  16
    ##  9 Mr. …        9 June  2014  2014-06-05 00:00:00        2.52                 14
    ## 10 Mr. …       10 June  2014  2014-06-11 00:00:00        3.76                 18
    ## # ℹ 996 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>

After cleaning, the dataset includes a total of 1006 observations, with
each observation representing a specific dumpster filled by one of the
trash wheels. The example of key variables include `date`, `month`,
`year`, `weight_tons`, and `cigarette_butts`. For available data, the
total weight of trash collected by Professor Trash Wheel was 233.26
tons. The total number of cigarette butts collected by Gwynnda in June
of 2022 was 1.812^{4}.

### Problem 3

First part

``` r
bakers = read_csv("data/bakers.csv") %>%
  janitor::clean_names() |>
  rename(baker = baker_name)
```

    ## Rows: 120 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker Name, Baker Occupation, Hometown
    ## dbl (2): Series, Baker Age
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
bakes = read_csv("data/bakes.csv") %>%
  janitor::clean_names()
```

    ## Rows: 548 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker, Signature Bake, Show Stopper
    ## dbl (2): Series, Episode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
results = read_csv("data/results.csv", skip = 2) 
```

    ## Rows: 1136 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (2): baker, result
    ## dbl (3): series, episode, technical
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
colnames(results) <- c("series", "episode", "baker", "technical", "result")

results_cleaned = results %>%
  filter(!is.na(series) & !is.na(episode) & !is.na(baker))
```

``` r
bakers_bakes = 
  left_join(bakes, bakers, by = c("baker", "series"))
```

``` r
final_dataset = 
  left_join(bakers_bakes, results_cleaned, by = c("series", "episode", "baker"))
```

``` r
final_dataset <- final_dataset %>%
  select(series, episode, baker, baker_age, baker_occupation, hometown, signature_bake, show_stopper, technical, result)
```

``` r
write_csv(final_dataset, "data/final_bake_dataset.csv")
```

First, I imported the data using `read_csv` and renamed each column to
something easier to work with. I renamed `baker_name` to `baker`,
removed the first two rows for the results dataset, and removed rows
with all `NA` values in the results dataset. I merged bakers and bakes
datasets based on `baker` and `series`, and then merged the combined
dataset with the results dataset on `series`, `episode`, and `baker`.
Finally, I reordered the columns and exported the CSV file.

Part two

``` r
star_bakers = final_dataset %>%
  filter(series >= 5 & series <= 10, result == "Star Baker") |>
  select(series, episode, baker)

print(star_bakers)
```

    ## # A tibble: 0 × 3
    ## # ℹ 3 variables: series <dbl>, episode <dbl>, baker <chr>
